
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPAccessorClassService", targetNamespace = "http://SOAP/", wsdlLocation = "http://localhost:8198/accessor?wsdl")
public class SOAPAccessorClassService
    extends Service
{

    private final static URL SOAPACCESSORCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPACCESSORCLASSSERVICE_EXCEPTION;
    private final static QName SOAPACCESSORCLASSSERVICE_QNAME = new QName("http://SOAP/", "SOAPAccessorClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8198/accessor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPACCESSORCLASSSERVICE_WSDL_LOCATION = url;
        SOAPACCESSORCLASSSERVICE_EXCEPTION = e;
    }

    public SOAPAccessorClassService() {
        super(__getWsdlLocation(), SOAPACCESSORCLASSSERVICE_QNAME);
    }

    public SOAPAccessorClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPACCESSORCLASSSERVICE_QNAME, features);
    }

    public SOAPAccessorClassService(URL wsdlLocation) {
        super(wsdlLocation, SOAPACCESSORCLASSSERVICE_QNAME);
    }

    public SOAPAccessorClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPACCESSORCLASSSERVICE_QNAME, features);
    }

    public SOAPAccessorClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPAccessorClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPAccessorClass
     */
    @WebEndpoint(name = "SOAPAccessorClassPort")
    public SOAPAccessorClass getSOAPAccessorClassPort() {
        return super.getPort(new QName("http://SOAP/", "SOAPAccessorClassPort"), SOAPAccessorClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPAccessorClass
     */
    @WebEndpoint(name = "SOAPAccessorClassPort")
    public SOAPAccessorClass getSOAPAccessorClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAP/", "SOAPAccessorClassPort"), SOAPAccessorClass.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPACCESSORCLASSSERVICE_EXCEPTION!= null) {
            throw SOAPACCESSORCLASSSERVICE_EXCEPTION;
        }
        return SOAPACCESSORCLASSSERVICE_WSDL_LOCATION;
    }

}
